version: '3'

services:
  db:
    container_name: txt-file-db
    image: mysql:5.6
    volumes:
    - ./.data:/var/lib/mysql
    - ./script.sql:/sql/script.sql
    ports:
    - "9999:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
